/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n\tmutation Login(\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerAccessTokenCreate(\n\t\t\tinput: { email: $email, password: $password }\n\t\t) {\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n": types.LoginDocument,
    "\n\tmutation Signup(\n\t\t$firstName: String!\n\t\t$lastName: String!\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerCreate(\n\t\t\tinput: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n": types.SignupDocument,
    "\n\tmutation UpdateCustomer(\n\t\t$customerAccessToken: String!\n\t\t$firstName: String\n\t\t$lastName: String\n\t\t$email: String\n\t\t$password: String\n\t) {\n\t\tcustomerUpdate(\n\t\t\tcustomerAccessToken: $customerAccessToken, customer: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\tdisplayName\n\t\t\t}\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\t\t\t\n": types.UpdateCustomerDocument,
    "\n\tmutation CartCreate {\n\t\tcartCreate {\n\t\t\tcart {\n\t\t\t\tid\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n": types.CartCreateDocument,
    "\n\tquery GetCollection(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$sortKey: ProductCollectionSortKeys!\n\t\t$filters: [ProductFilter!]\n\t\t$reverse: Boolean = false\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\ttitle\n\t\t\tproducts(first: $limit, sortKey: $sortKey, reverse: $reverse, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t\thandle\n\t\t\t\t\tdescription\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tfeaturedImage {\n\t\t\t\t\t\tsrc\n\t\t\t\t\t\twidth\n\t\t\t\t\t\theight\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tpageInfo {\n\t\t\t\t\thasNextPage\n\t\t\t\t}\n\t\t\t\tfilters {\n\t\t\t\t\tlabel\n\t\t\t\t\tvalues {\n\t\t\t\t\t\tlabel\n\t\t\t\t\t\tinput\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetCollectionDocument,
    "\n\tquery GetCollectionMaxPrice(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$filters: [ProductFilter!]\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\tproducts(first: $limit, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetCollectionMaxPriceDocument,
    "\n\tquery GetProduct($handle: String!) {\n\t\tproductByHandle(handle: $handle) {\n\t\t\tdescription\n\t\t\thandle\n\t\t\tid\n\t\t\tproductType\n\t\t\ttags\n\t\t\ttitle\n\t\t\tvendor\n\t\t\timages(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\taltText\n\t\t\t\t\theight\n\t\t\t\t\tid\n\t\t\t\t\tsrc\n\t\t\t\t\twidth\n\t\t\t\t}\n\t\t\t}\n\t\t\tvariants(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tid\n\t\t\t\t\tquantityAvailable\n\t\t\t\t\ttitle\n\t\t\t\t\tcompareAtPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tpriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetProductDocument,
    "\n\tfragment AddressFields on MailingAddress {\n\t\taddress1\n\t\taddress2\n\t\tcity\n\t\tformatted(withName: true)\n\t\tformattedArea\n\t\tid\n\t\tlastName\n\t\tname\n\t\tphone\n\t\tprovinceCode\n\t\tzip\n\t\tfirstName\n\t\tcountry\n\t}\n": types.AddressFieldsFragmentDoc,
    "\n\tquery GetCustomer(\n\t\t$customerAccessToken: String!\n\t) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tacceptsMarketing\n\t\t\tcreatedAt\n\t\t\tdisplayName\n\t\t\temail\n\t\t\tfirstName\n\t\t\tid\n\t\t\tlastName\n\t\t\tnumberOfOrders\n\t\t\tphone\n\t\t\ttags\n\t\t\tupdatedAt\n\t\t\taddresses(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\t...AddressFields\n\t\t\t\t}\n\t\t\t}\n\t\t\tdefaultAddress {\n\t\t\t\t...AddressFields\n\t\t\t}\n\t\t\torders(first: 10, sortKey: PROCESSED_AT) {\n\t\t\t\ttotalCount\n\t\t\t\tnodes {\n\t\t\t\t\tcancelReason\n\t\t\t\t\tcanceledAt\n\t\t\t\t\tcurrencyCode\n\t\t\t\t\tcustomerLocale\n\t\t\t\t\tcustomerUrl\n\t\t\t\t\tedited\n\t\t\t\t\temail\n\t\t\t\t\tfinancialStatus\n\t\t\t\t\tfulfillmentStatus\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\torderNumber\n\t\t\t\t\tphone\n\t\t\t\t\tprocessedAt\n\t\t\t\t\tstatusUrl\n\t\t\t\t\tbillingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\tlineItems {\n\t\t\t\t\t\tnodes {\n\t\t\t\t\t\t\tcurrentQuantity\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\toriginalTotalPrice {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tshippingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\ttotalPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\ttotalShippingPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetCustomerDocument,
    "\n\tquery Customer($customerAccessToken: String!) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tid\n\t\t}\n\t}\n": types.CustomerDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation Login(\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerAccessTokenCreate(\n\t\t\tinput: { email: $email, password: $password }\n\t\t) {\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation Login(\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerAccessTokenCreate(\n\t\t\tinput: { email: $email, password: $password }\n\t\t) {\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation Signup(\n\t\t$firstName: String!\n\t\t$lastName: String!\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerCreate(\n\t\t\tinput: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation Signup(\n\t\t$firstName: String!\n\t\t$lastName: String!\n\t\t$email: String!\n\t\t$password: String!\n\t) {\n\t\tcustomerCreate(\n\t\t\tinput: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateCustomer(\n\t\t$customerAccessToken: String!\n\t\t$firstName: String\n\t\t$lastName: String\n\t\t$email: String\n\t\t$password: String\n\t) {\n\t\tcustomerUpdate(\n\t\t\tcustomerAccessToken: $customerAccessToken, customer: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\tdisplayName\n\t\t\t}\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\t\t\t\n"): (typeof documents)["\n\tmutation UpdateCustomer(\n\t\t$customerAccessToken: String!\n\t\t$firstName: String\n\t\t$lastName: String\n\t\t$email: String\n\t\t$password: String\n\t) {\n\t\tcustomerUpdate(\n\t\t\tcustomerAccessToken: $customerAccessToken, customer: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }\n\t\t) {\n\t\t\tcustomer {\n\t\t\t\tid\n\t\t\t\temail\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\tdisplayName\n\t\t\t}\n\t\t\tcustomerAccessToken {\n\t\t\t\taccessToken\n\t\t\t\texpiresAt\n\t\t\t}\n\t\t\tcustomerUserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\t\t\t\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CartCreate {\n\t\tcartCreate {\n\t\t\tcart {\n\t\t\t\tid\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CartCreate {\n\t\tcartCreate {\n\t\t\tcart {\n\t\t\t\tid\n\t\t\t}\n\t\t\tuserErrors {\n\t\t\t\tcode\n\t\t\t\tfield\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetCollection(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$sortKey: ProductCollectionSortKeys!\n\t\t$filters: [ProductFilter!]\n\t\t$reverse: Boolean = false\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\ttitle\n\t\t\tproducts(first: $limit, sortKey: $sortKey, reverse: $reverse, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t\thandle\n\t\t\t\t\tdescription\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tfeaturedImage {\n\t\t\t\t\t\tsrc\n\t\t\t\t\t\twidth\n\t\t\t\t\t\theight\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tpageInfo {\n\t\t\t\t\thasNextPage\n\t\t\t\t}\n\t\t\t\tfilters {\n\t\t\t\t\tlabel\n\t\t\t\t\tvalues {\n\t\t\t\t\t\tlabel\n\t\t\t\t\t\tinput\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetCollection(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$sortKey: ProductCollectionSortKeys!\n\t\t$filters: [ProductFilter!]\n\t\t$reverse: Boolean = false\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\ttitle\n\t\t\tproducts(first: $limit, sortKey: $sortKey, reverse: $reverse, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t\thandle\n\t\t\t\t\tdescription\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tfeaturedImage {\n\t\t\t\t\t\tsrc\n\t\t\t\t\t\twidth\n\t\t\t\t\t\theight\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tpageInfo {\n\t\t\t\t\thasNextPage\n\t\t\t\t}\n\t\t\t\tfilters {\n\t\t\t\t\tlabel\n\t\t\t\t\tvalues {\n\t\t\t\t\t\tlabel\n\t\t\t\t\t\tinput\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetCollectionMaxPrice(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$filters: [ProductFilter!]\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\tproducts(first: $limit, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetCollectionMaxPrice(\n\t\t$handle: String!\n\t\t$limit: Int!\n\t\t$filters: [ProductFilter!]\n\t) {\n\t\tcollection(handle: $handle) {\n\t\t\tproducts(first: $limit, filters: $filters) {\n\t\t\t\tnodes {\n\t\t\t\t\tpriceRange {\n\t\t\t\t\t\tmaxVariantPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetProduct($handle: String!) {\n\t\tproductByHandle(handle: $handle) {\n\t\t\tdescription\n\t\t\thandle\n\t\t\tid\n\t\t\tproductType\n\t\t\ttags\n\t\t\ttitle\n\t\t\tvendor\n\t\t\timages(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\taltText\n\t\t\t\t\theight\n\t\t\t\t\tid\n\t\t\t\t\tsrc\n\t\t\t\t\twidth\n\t\t\t\t}\n\t\t\t}\n\t\t\tvariants(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tid\n\t\t\t\t\tquantityAvailable\n\t\t\t\t\ttitle\n\t\t\t\t\tcompareAtPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tpriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetProduct($handle: String!) {\n\t\tproductByHandle(handle: $handle) {\n\t\t\tdescription\n\t\t\thandle\n\t\t\tid\n\t\t\tproductType\n\t\t\ttags\n\t\t\ttitle\n\t\t\tvendor\n\t\t\timages(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\taltText\n\t\t\t\t\theight\n\t\t\t\t\tid\n\t\t\t\t\tsrc\n\t\t\t\t\twidth\n\t\t\t\t}\n\t\t\t}\n\t\t\tvariants(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\tavailableForSale\n\t\t\t\t\tid\n\t\t\t\t\tquantityAvailable\n\t\t\t\t\ttitle\n\t\t\t\t\tcompareAtPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tpriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tfragment AddressFields on MailingAddress {\n\t\taddress1\n\t\taddress2\n\t\tcity\n\t\tformatted(withName: true)\n\t\tformattedArea\n\t\tid\n\t\tlastName\n\t\tname\n\t\tphone\n\t\tprovinceCode\n\t\tzip\n\t\tfirstName\n\t\tcountry\n\t}\n"): (typeof documents)["\n\tfragment AddressFields on MailingAddress {\n\t\taddress1\n\t\taddress2\n\t\tcity\n\t\tformatted(withName: true)\n\t\tformattedArea\n\t\tid\n\t\tlastName\n\t\tname\n\t\tphone\n\t\tprovinceCode\n\t\tzip\n\t\tfirstName\n\t\tcountry\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetCustomer(\n\t\t$customerAccessToken: String!\n\t) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tacceptsMarketing\n\t\t\tcreatedAt\n\t\t\tdisplayName\n\t\t\temail\n\t\t\tfirstName\n\t\t\tid\n\t\t\tlastName\n\t\t\tnumberOfOrders\n\t\t\tphone\n\t\t\ttags\n\t\t\tupdatedAt\n\t\t\taddresses(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\t...AddressFields\n\t\t\t\t}\n\t\t\t}\n\t\t\tdefaultAddress {\n\t\t\t\t...AddressFields\n\t\t\t}\n\t\t\torders(first: 10, sortKey: PROCESSED_AT) {\n\t\t\t\ttotalCount\n\t\t\t\tnodes {\n\t\t\t\t\tcancelReason\n\t\t\t\t\tcanceledAt\n\t\t\t\t\tcurrencyCode\n\t\t\t\t\tcustomerLocale\n\t\t\t\t\tcustomerUrl\n\t\t\t\t\tedited\n\t\t\t\t\temail\n\t\t\t\t\tfinancialStatus\n\t\t\t\t\tfulfillmentStatus\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\torderNumber\n\t\t\t\t\tphone\n\t\t\t\t\tprocessedAt\n\t\t\t\t\tstatusUrl\n\t\t\t\t\tbillingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\tlineItems {\n\t\t\t\t\t\tnodes {\n\t\t\t\t\t\t\tcurrentQuantity\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\toriginalTotalPrice {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tshippingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\ttotalPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\ttotalShippingPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetCustomer(\n\t\t$customerAccessToken: String!\n\t) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tacceptsMarketing\n\t\t\tcreatedAt\n\t\t\tdisplayName\n\t\t\temail\n\t\t\tfirstName\n\t\t\tid\n\t\t\tlastName\n\t\t\tnumberOfOrders\n\t\t\tphone\n\t\t\ttags\n\t\t\tupdatedAt\n\t\t\taddresses(first: 10) {\n\t\t\t\tnodes {\n\t\t\t\t\t...AddressFields\n\t\t\t\t}\n\t\t\t}\n\t\t\tdefaultAddress {\n\t\t\t\t...AddressFields\n\t\t\t}\n\t\t\torders(first: 10, sortKey: PROCESSED_AT) {\n\t\t\t\ttotalCount\n\t\t\t\tnodes {\n\t\t\t\t\tcancelReason\n\t\t\t\t\tcanceledAt\n\t\t\t\t\tcurrencyCode\n\t\t\t\t\tcustomerLocale\n\t\t\t\t\tcustomerUrl\n\t\t\t\t\tedited\n\t\t\t\t\temail\n\t\t\t\t\tfinancialStatus\n\t\t\t\t\tfulfillmentStatus\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\torderNumber\n\t\t\t\t\tphone\n\t\t\t\t\tprocessedAt\n\t\t\t\t\tstatusUrl\n\t\t\t\t\tbillingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\tlineItems {\n\t\t\t\t\t\tnodes {\n\t\t\t\t\t\t\tcurrentQuantity\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\toriginalTotalPrice {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\tshippingAddress {\n\t\t\t\t\t\t...AddressFields\n\t\t\t\t\t}\n\t\t\t\t\ttotalPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t\ttotalShippingPriceV2 {\n\t\t\t\t\t\tamount\n\t\t\t\t\t\tcurrencyCode\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery Customer($customerAccessToken: String!) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery Customer($customerAccessToken: String!) {\n\t\tcustomer(customerAccessToken: $customerAccessToken) {\n\t\t\tid\n\t\t}\n\t}\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;