import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import Header from '@/components/Header/Header'
import { cn } from '@/lib/utils/cn'
import { ApolloWrapper } from '@/lib/apollo/apolloWrapper'
import '@/styles/globals.css'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<React.PropsWithChildren>) {
	return (
		<html lang="en">
			<body className={cn('', fontSans.className)}>
				<ApolloWrapper>
					<Header />
					<main className="flex justify-center mx-auto max-w-[1366px]">{children}</main>
				</ApolloWrapper>
			</body>
		</html>
	)
}
