name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1

    - name: Cache Docker layers
      uses: actions/cache@v4.0.2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag clairox/bordz:latest --tag clairox/bordz:${{ github.sha }} --load .

    - name: List
      run: docker run clairox/bordz:latest ls /app
      
    - name: Run tests in Docker container
      run: docker buildx build --target tester --load . && docker run --rm clairox/bordz:tester CI=true npm test
            
            
